# Project Description:

There are 4 source systems in this project from where we need to load data in python data frames.

All these source systems are some third party databases, and have similar schema. For one of the source that is CSV_1, we also got source schema extract to understand the fields definition.

Note- Same schema is applicable for all 4 source systems datasets.

Each data source system contains 3 types of datasets named Customers, Products and Transaction.

**Use cases:**

**Usecase 1 to Usecase 7 (about csv)**

Usecase-1 Load all three csv datasets in Pandas DataFrames and display first 5 records.

In [1]:
import pandas as pd

In [2]:
cust1 = pd.read_csv('customers.csv',names = ['custno','firstname','lastname','gender','age','profession','contactNo','emailId','city','state','isActive','createdDate','UpdateDate'])
prod1 = pd.read_csv('products.csv',names = ['productno','productName','Description','isActive','createdDate','UpdatedDate'])
tran1 = pd.read_csv('transactions.csv',names = ['txnno','txndate','custno','amount','productno','spendby'])

In [3]:
cust1.head(5)

,custno,firstname,lastname,gender,age,profession,contactNo,emailId,city,state,isActive,createdDate,UpdateDate
0,1,Leslie,Bass,F,27,B,37307,endslost@everyma1l.org,Gibson,Dellwood,Y,2017-09-21 12:38:22,2017-10-18 12:12:28
1,2,Judy,Burks,M,53,S,84759,rfleming@hotma1l.co.uk,Suwanee,Trabue,Y,2017-05-22 05:29:22,2017-10-18 12:12:28
2,3,Marsha,Doyle,F,48,B,80932,arethe53@ma1lbox.net,Perry,Moxadarla,Y,2017-09-03 12:11:29,2017-10-18 12:12:28
3,4,Alexis,Battle,M,27,S,71701,ofcame@ma1lbox.org,Morven,Dennis,Y,2017-02-16 04:05:35,2017-10-18 12:12:28
4,5,Martha,Combs,F,49,B,83947,camedied@everyma1l.us,Ocilla,Greenwood,Y,2017-05-15 07:34:35,2017-10-18 12:12:28

In [4]:
prod1.head(5)

,productno,productName,Description,isActive,createdDate,UpdatedDate
0,1,Product1,pgqorighfa,Y,2017-04-03 07:58:55,2017-10-18 12:12:38
1,2,Product2,lmndaaweth,Y,2017-09-21 12:38:31,2017-10-18 12:12:38
2,3,Product3,urifeubrhh,Y,2017-09-08 10:32:12,2017-10-18 12:12:38
3,4,Product4,rlpcjxfarp,Y,2017-05-22 05:29:27,2017-10-18 12:12:38
4,5,Product5,hzcpozsgfc,Y,2017-02-02 08:40:29,2017-10-18 12:12:38

In [5]:
tran1.head(5)

   txnno              txndate  custno  amount  productno spendby
0      1  2017-10-18 12:31:45     923    2559        376    Card
1      2  2017-10-18 12:31:45     219    1706        151    Card
2      3  2017-10-18 12:31:45     927    3462        707    Cash
3      4  2017-10-18 12:31:45     806     865        539    Card
4      5  2017-10-18 12:31:45     958    2494         25    Card

Usecase-2 Display only those customers from CSV_s1, who purchased more than 3 products.

In [6]:
prodcount = tran1.groupby('custno')['productno'].count()
prodcount1 = prodcount.reset_index()
prodcount1[prodcount1['productno']>3]

     custno  productno
2         4          4
49       86          4
100     167          4
111     187          4
145     237          4
147     241          5
193     321          4
196     326          4
200     331          4
219     356          4
242     391          5
340     537          4
355     558          4
366     578          4
449     709          4
463     735          4
472     753          4
525     828          4
641     989          4

In [7]:
prodcount = tran1.groupby('custno')['productno'].count()
prodcount1 = prodcount.reset_index()
prodcount1.sort_values('productno', ascending = False)
#prodcount1[prodcount1['productno']>3]

     custno  productno
242     391          5
147     241          5
355     558          4
111     187          4
100     167          4
..      ...        ...
356     559          1
125     207          1
354     556          1
126     208          1
647     999          1

[648 rows x 2 columns]

In [8]:
cust1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   custno       1000 non-null   int64
 1   firstname    1000 non-null   object
 2   lastname     1000 non-null   object
 3   gender       1000 non-null   object
 4   age          1000 non-null   int64
 5   profession   1000 non-null   object
 6   contactNo    1000 non-null   int64
 7   emailId      1000 non-null   object
 8   city         1000 non-null   object
 9   state        1000 non-null   object
 10  isActive     1000 non-null   object
 11  createdDate  1000 non-null   object
 12  UpdateDate   1000 non-null   object
dtypes: int64(3), object(10)
memory usage: 101.7+ KB

In [9]:
tran1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   txnno      1000 non-null   int64
 1   txndate    1000 non-null   object
 2   custno     1000 non-null   int64
 3   amount     1000 non-null   int64
 4   productno  1000 non-null   int64
 5   spendby    1000 non-null   object
dtypes: int64(4), object(2)
memory usage: 47.0+ KB

In [10]:
merged = cust1.merge(tran1, on = 'custno', how = 'right')
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   custno       1000 non-null   int64
 1   firstname    1000 non-null   object
 2   lastname     1000 non-null   object
 3   gender       1000 non-null   object
 4   age          1000 non-null   int64
 5   profession   1000 non-null   object
 6   contactNo    1000 non-null   int64
 7   emailId      1000 non-null   object
 8   city         1000 non-null   object
 9   state        1000 non-null   object
 10  isActive     1000 non-null   object
 11  createdDate  1000 non-null   object
 12  UpdateDate   1000 non-null   object
 13  txnno        1000 non-null   int64
 14  txndate      1000 non-null   object
 15  amount       1000 non-null   int64
 16  productno    1000 non-null   int64
 17  spendby      1000 non-null   object
dtypes: int64(6), object(12)
memory usage: 148.4+ KB

In [11]:
merged = cust1.merge(tran1, on = 'custno', how = 'inner')
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   custno       1000 non-null   int64
 1   firstname    1000 non-null   object
 2   lastname     1000 non-null   object
 3   gender       1000 non-null   object
 4   age          1000 non-null   int64
 5   profession   1000 non-null   object
 6   contactNo    1000 non-null   int64
 7   emailId      1000 non-null   object
 8   city         1000 non-null   object
 9   state        1000 non-null   object
 10  isActive     1000 non-null   object
 11  createdDate  1000 non-null   object
 12  UpdateDate   1000 non-null   object
 13  txnno        1000 non-null   int64
 14  txndate      1000 non-null   object
 15  amount       1000 non-null   int64
 16  productno    1000 non-null   int64
 17  spendby      1000 non-null   object
dtypes: int64(6), object(12)
memory usage: 148.4+ KB

In [12]:
prodcount = merged.groupby(['custno','firstname'])['productno'].count()
prodcount1 = prodcount.reset_index()
prodcount1.sort_values('productno', ascending = False)
#prodcount1[prodcount1['productno']>3]

     custno firstname  productno
242     391     Keith          5
147     241   Derrick          5
355     558      Lois          4
111     187      Alan          4
100     167     Alice          4
..      ...       ...        ...
356     559   Patrick          1
125     207   Anthony          1
354     556  Jonathon          1
126     208      Baby          1
647     999     Betty          1

[648 rows x 3 columns]

Usecase-3 Display top 5 most demanded products from CSV_s1

In [13]:
data = pd.merge(tran1,cust1[['custno','firstname','lastname']], on = 'custno')
data1 = pd.merge(data,prod1[['productno', 'productName']], on = 'productno')
product_demand = data1['productName'].value_counts().nlargest(5).reset_index()
product_demand.columns =['product_name','Demand']
product_demand

  product_name  Demand
0    Product82       5
1   Product768       5
2   Product427       5
3   Product900       5
4   Product233       4

Usecase-4 Display top 5 transactions amount from CSV_s1

In [14]:
tran1.nlargest(5,'amount')

     txnno              txndate  custno  amount  productno spendby
556    557  2017-10-18 12:31:46     670    4996        509    Card
305    306  2017-10-18 12:31:46     448    4992        427    Cash
574    575  2017-10-18 12:31:46     305    4981        549    Card
531    532  2017-10-18 12:31:46     230    4980        658    Card
232    233  2017-10-18 12:31:45     287    4966        685    Card

Usecase-5 Display distinct professions from CSV_s1

In [15]:
cust1['profession'].unique()

array(['B', 'S'], dtype=object)

Usecase-6 Display highest age in CSV_s1 customer's dataset

In [16]:
cust1['age'].max()

64

In [17]:
cust1.nlargest(1, 'age')

,custno,firstname,lastname,gender,age,profession,contactNo,emailId,city,state,isActive,createdDate,UpdateDate
58,59,Randall,Lambert,F,64,B,41458,throwfrom@hotma1l.com,Broxton,Louise,Y,2017-10-10 09:57:25,2017-10-18 12:12:28

Usecase-7 Display custno, gender, age, profession, contactno, productno, productname, txndate, spendby, amount, from CSV_s1 for custno = 923

In [18]:
cust1[cust1['custno']==923]

,custno,firstname,lastname,gender,age,profession,contactNo,emailId,city,state,isActive,createdDate,UpdateDate
922,923,Russell,Walters,F,46,B,25436,esears55@ma1lbox.us,Cuthbert,Odell,Y,2017-07-30 01:30:09,2017-10-18 12:12:29

Usecase-8 Load all three PSV (pipe separated values) dataset in Pandas DataFrames and display first 5 records.

In [19]:
psvcust1 = pd.read_csv('customers.txt',sep='|',header=None,names=['custno','firstname','lastname','gender','age','profession','contactNo','emailId','city','state','isActive','createdDate','UpdateDate'])
psvprod1 = pd.read_csv('products.txt',sep='|',header=None,names= ['productno','productName','Description','isActive','createdDate','UpdatedDate'])
psvtran1 = pd.read_csv('transactions.txt',sep='|',header=None,names= ['txnno','txndate','custno','amount','productno','spendby'])

In [20]:
psvcust1.head(5)

,custno,firstname,lastname,gender,age,profession,contactNo,emailId,city,state,isActive,createdDate,UpdateDate
0,1,Leslie,Bass,F,27,B,37307,endslost@everyma1l.org,Gibson,Dellwood,Y,2017-09-21 12:38:22,2017-10-18 12:12:28
1,2,Judy,Burks,M,53,S,84759,rfleming@hotma1l.co.uk,Suwanee,Trabue,Y,2017-05-22 05:29:22,2017-10-18 12:12:28
2,3,Marsha,Doyle,F,48,B,80932,arethe53@ma1lbox.net,Perry,Moxadarla,Y,2017-09-03 12:11:29,2017-10-18 12:12:28
3,4,Alexis,Battle,M,27,S,71701,ofcame@ma1lbox.org,Morven,Dennis,Y,2017-02-16 04:05:35,2017-10-18 12:12:28
4,5,Martha,Combs,F,49,B,83947,camedied@everyma1l.us,Ocilla,Greenwood,Y,2017-05-15 07:34:35,2017-10-18 12:12:28

Usecase-9 Load all three Json datsets in Pandas DataFrames and display first 5 records.

In [21]:
custjson = pd.read_json('customers.json', lines = True)
prodjson = pd.read_json('products.json', lines = True)
tranjson = pd.read_json('transactions.json', lines = True)

In [22]:
custjson.head(5)

,custno,firstname,lastname,gender,age,profession,contactNo,emailId,city,state,isActive,createdDate,UpdatedDate
0,1,Dai,Noble,2,53,Human Resources,1644101928099,eu.lacus.Quisque@loremac.com,Berlin,Berlin,1,2017-03-01,2018-08-25
1,2,Kay,Wise,2,26,Public Relations,1674031917099,ridiculus@Sednunc.ca,Oldenzaal,Overijssel,2,2017-04-10,2018-08-30
2,3,Amir,Pace,1,43,Customer Relations,1636050509999,quam.Pellentesque@erat.edu,Cobourg,Ontario,2,2017-03-04,2018-09-18
3,4,Sebastian,Lopez,2,32,Customer Relations,1666010108899,magna@venenatis.net,Te Awamutu,NI,1,2016-12-17,2018-09-12
4,5,Brian,Maddox,1,40,Quality Assurance,1646080399299,ac.facilisis@Duis.com,Greater Sudbury,Ontario,2,2017-02-18,2018-05-13

Usecase-10 Load all three XML datasets in Pandas DataFrames and display first 5 records.

In [23]:
xmlcust = pd.read_xml('customers.xml')
xmlprod = pd.read_xml('products.xml')
xmltran = pd.read_xml('transactions.xml')

In [24]:
xmlcust.head(5)

,custno,firstname,lastname,gender,age,profession,contactNo,emailId,city,state,isActive,createdDate,UpdatedDate
0,1,Teegan,Hubbard,2,33,Human Resources,1681121691699,nibh.Quisque@placerat.com,Galashiels,Selkirkshire,1,2016-12-07,2018-09-05
1,2,Deacon,Briggs,2,54,Customer Relations,1631082682999,facilisis.eget@Nullaeu.com,Lens-Saint-Remy,LU,1,2017-04-26,2018-06-04
2,3,Mallory,Shelton,1,57,Customer Relations,1627011572699,Curabitur.ut@Nullatempor.edu,North Shore,NI,1,2017-01-02,2018-08-01
3,4,Quinn,Clements,2,43,Media Relations,1618122268999,metus.Vivamus.euismod@urna.edu,Heredia,H,1,2017-02-11,2018-07-18
4,5,Arthur,Hurst,2,41,Tech Support,1681021022799,in@commodoipsum.org,San Diego,Cartago,2,2017-03-30,2018-05-19

GitHub: https://github.com/abhishekpatelsk/E_Commerce_Data_Analysis_with_Python


Thank you!

**- Abhishek Patel**